import { register } from "node:module";
import { readFileSync } from "node:fs";
import assert from "node:assert/strict";
register('data:text/javascript,export async function resolve(s,c,n){try{return await n(s,c)}catch(e){if(s.startsWith(".")&&!s.endsWith(".js"))return n(s+".js",c);throw e}}', import.meta.url);
const { deriveAfty } = await import("../afty-derive.js");
const { createBlankAfty } = await import("../afty-schema.js");
const { aplicarAddons, validarPacote, limparAddons } = await import("../afty-addons.js");
const { getEquipamento, novaEntradaEquip } = await import("../afty-equipamentos.js");
const { estadoForma, alteraArmaTransformavel: altera, avancaArmasTransformaveis } = await import("../afty-armas-transformaveis.js");
const { gastaPe, proximaRodada, iniciaCombate } = await import("../ficha/ficha-sessao.js");
const alteraArmaTransformavel = (s, a, e) => altera(s, a, e, gastaPe);
const pacote = JSON.parse(readFileSync(new URL("../azamaru.json", import.meta.url), "utf8"));
assert.deepEqual(validarPacote(pacote), []);
assert.deepEqual(aplicarAddons([pacote]).problemas, []);
const ficha = createBlankAfty();
ficha.core.nd = 13;
ficha.addons = [pacote];
const id = "azamaru:azamaru";
const def = getEquipamento("arma", id, ficha);
ficha.equipamentos.itens = [novaEntradaEquip("arma", id, def)];
let sessao = { peAtual: 50, rodada: 1, combate: { ativo: true } };
const derivar = () => deriveAfty({ ...ficha, combate: sessao.combate });
const base = derivar();
const arma = base.armasTransformaveis[0];
assert.ok(arma);
assert.equal(arma.bt, 5);
sessao = alteraArmaTransformavel(sessao, arma, "reunir");
assert.equal(sessao.peAtual, 50);
assert.equal(estadoForma(sessao.combate, id).clones, 5);
const reunida = derivar();
assert.equal(reunida.defesa - base.defesa, 10);
const reflexos = (d) => d.testes.resistencias.find((r) => r.value === "reflexos").bonus;
assert.equal(reflexos(reunida) - reflexos(base), 10);
const dano = (d) => d.dano.entradas.find((e) => e.id === id);
assert.equal(dano(reunida).ignoraTodaRD, true);
assert.equal(dano(reunida).ignoraImunidade, true);
assert.equal(dano(reunida).removeResistencia, true);
assert.equal(dano(base).ignoraTodaRD, false);
assert.equal(getEquipamento("arma", id, { ...ficha, combate: sessao.combate }).props.pesada, undefined);
sessao = alteraArmaTransformavel(sessao, arma, "golpe");
assert.equal(derivar().defesa - base.defesa, 8);
sessao = alteraArmaTransformavel(sessao, arma, "todos");
assert.equal(estadoForma(sessao.combate, id).reserva, 5);
assert.equal(derivar().defesa, base.defesa);
assert.notEqual(dano(derivar()).texto, dano(reunida).texto);
sessao = alteraArmaTransformavel(sessao, arma, "acerto");
assert.equal(estadoForma(sessao.combate, id).reserva, 1);
sessao = avancaArmasTransformaveis({ ...sessao, rodada: 2 });
assert.equal(estadoForma(sessao.combate, id).reserva, 0);
sessao = alteraArmaTransformavel(sessao, arma, "dividir");
assert.equal(alteraArmaTransformavel(sessao, arma, "reunir"), sessao);
sessao = { ...sessao, rodada: 3 };
sessao = alteraArmaTransformavel(sessao, arma, "reunir");
assert.equal(sessao.peAtual, 45);
sessao = avancaArmasTransformaveis(sessao, true);
assert.equal(estadoForma(sessao.combate, id).usos, 0);
sessao = alteraArmaTransformavel(sessao, arma, "reunir");
assert.equal(sessao.peAtual, 45);
const semArma = deriveAfty({ ...ficha, equipamentos: { itens: [] }, combate: sessao.combate });
assert.deepEqual(semArma.armasTransformaveis, []);
assert.deepEqual(deriveAfty({ ...ficha, addons: [], combate: sessao.combate }).armasTransformaveis, []);
const pc = def.criacao;
assert.equal(pc.pcDano + pc.pcCritico + pc.pcPropriedades, pc.pcTotal);
assert.ok(pc.pcDano <= pc.limiteDano && pc.pcPropriedades <= pc.limitePropriedades);
const custos = { fineza: 1, marcial: 1, dupla: 1, apunhaladora: 1, energica: 2,
  mortal: 2, oscilante: 1, ampla: 3, duas_maos: -1 };
for (const props of [def.props, def.formas.reunida.props]) {
  assert.equal(Object.keys(props).reduce((n, k) => n + custos[k], 0), pc.pcPropriedades);
}
ficha.rulesVersion = "player";
const jogador = derivar();
assert.ok(dano(jogador).gruposDano.some((g) => g.faces === 12));
assert.equal(dano(jogador).margemCritico, 18);
assert.equal(dano(jogador).ignoraTodaRD, true);
sessao = alteraArmaTransformavel(sessao, arma, "livre");
sessao = alteraArmaTransformavel(sessao, arma, "acerto");
assert.equal(estadoForma(sessao.combate, id).reserva, 1);
sessao = proximaRodada({ ...sessao, buffs: [], condicoes: [] }, jogador).sessao;
assert.equal(estadoForma(sessao.combate, id).reserva, 0);
sessao = alteraArmaTransformavel(sessao, arma, "dividir");
sessao = { ...sessao, rodada: sessao.rodada + 1, peAtual: 0 };
assert.equal(alteraArmaTransformavel(sessao, arma, "reunir"), sessao);
sessao.peTempFontes = { teste: 5 };
sessao = alteraArmaTransformavel(sessao, arma, "reunir");
assert.equal(sessao.peAtual, 0);
assert.equal(Object.values(sessao.peTempFontes).reduce((n, v) => n + v, 0), 0);
sessao = iniciaCombate(sessao, jogador);
assert.equal(estadoForma(sessao.combate, id).usos, 0);
assert.equal(estadoForma(sessao.combate, id).clones, 0);
limparAddons();
console.log("Azamaru: pacote, deriveAfty, clones, custos, formas, isolamento e orçamento passaram.");
